In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('flight_data_2018_2024.csv')

<ipython-input-45-791efcd94eec>:1: DtypeWarning: Columns (11,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('flight_data_2018_2024.csv')


In [ ]:
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0      2024        1      1          14          7  2024-01-14   
1      2024        1      1          14          7  2024-01-14   
2      2024        1      1          14          7  2024-01-14   
3      2024        1      1          14          7  2024-01-14   
4      2024        1      1          14          7  2024-01-14   
...     ...      ...    ...         ...        ...         ...   
23401  2024        1      1          17          3  2024-01-17   
23402  2024        1      1          17          3  2024-01-17   
23403  2024        1      1          17          3  2024-01-17   
23404  2024        1      1          17          3  2024-01-17   
23405  2024        1      1          17          3  2024-01-17   

      Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
0                            UA                            UA_CODESHARE   
1                            UA                            UA_CODESHARE   
2                            UA                            UA_CODESHARE   
3                            UA                            UA_CODESHARE   
4                            UA                            UA_CODESHARE   
...                         ...                                     ...   
23401                        WN                                      WN   
23402                        WN                                      WN   
23403                        WN                                      WN   
23404                        WN                                      WN   
23405                        WN                                      WN   

       DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  Div5Airport  \
0                         19977                          UA  ...          NaN   
1                         19977                          UA  ...          NaN   
2                         19977                          UA  ...          NaN   
3                         19977                          UA  ...          NaN   
4                         19977                          UA  ...          NaN   
...                         ...                         ...  ...          ...   
23401                     19393                          WN  ...          NaN   
23402                     19393                          WN  ...          NaN   
23403                     19393                          WN  ...          NaN   
23404                     19393                          WN  ...          NaN   
23405                     19393                          WN  ...          NaN   

      Div5AirportID  Div5AirportSeqID Div5WheelsOn  Div5TotalGTime  \
0               NaN               NaN          NaN             NaN   
1               NaN               NaN          NaN             NaN   
2               NaN               NaN          NaN             NaN   
3               NaN               NaN          NaN             NaN   
4               NaN               NaN          NaN             NaN   
...             ...               ...          ...             ...   
23401           NaN               NaN          NaN             NaN   
23402           NaN               NaN          NaN             NaN   
23403           NaN               NaN          NaN             NaN   
23404           NaN               NaN          NaN             NaN   
23405           NaN               NaN          NaN             NaN   

      Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  Unnamed: 119  
0                  NaN            NaN         NaN         N           NaN  
1                  NaN            NaN         NaN         N           NaN  
2                  NaN            NaN         NaN         N           NaN  
3                  NaN            NaN         NaN         N           NaN  
4                  NaN            NaN         NaN         N           NaN  
...                ...            ...      

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23406 entries, 0 to 23405
Columns: 120 entries, Year to Unnamed: 119
dtypes: float64(75), int64(22), object(23)
memory usage: 21.4+ MB


In [ ]:
df.dropna(axis = 1, inplace = True)

In [ ]:
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0      2024        1      1          14          7  2024-01-14   
1      2024        1      1          14          7  2024-01-14   
2      2024        1      1          14          7  2024-01-14   
3      2024        1      1          14          7  2024-01-14   
4      2024        1      1          14          7  2024-01-14   
...     ...      ...    ...         ...        ...         ...   
23401  2024        1      1          17          3  2024-01-17   
23402  2024        1      1          17          3  2024-01-17   
23403  2024        1      1          17          3  2024-01-17   
23404  2024        1      1          17          3  2024-01-17   
23405  2024        1      1          17          3  2024-01-17   

      Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
0                            UA                            UA_CODESHARE   
1                            UA                            UA_CODESHARE   
2                            UA                            UA_CODESHARE   
3                            UA                            UA_CODESHARE   
4                            UA                            UA_CODESHARE   
...                         ...                                     ...   
23401                        WN                                      WN   
23402                        WN                                      WN   
23403                        WN                                      WN   
23404                        WN                                      WN   
23405                        WN                                      WN   

       DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  CRSDepTime  \
0                         19977                          UA  ...        1738   
1                         19977                          UA  ...         815   
2                         19977                          UA  ...        1540   
3                         19977                          UA  ...         630   
4                         19977                          UA  ...        1300   
...                         ...                         ...  ...         ...   
23401                     19393                          WN  ...         645   
23402                     19393                          WN  ...        1150   
23403                     19393                          WN  ...         620   
23404                     19393                          WN  ...        1750   
23405                     19393                          WN  ...        1725   

      DepTimeBlk  CRSArrTime ArrTimeBlk  Cancelled  Diverted  CRSElapsedTime  \
0      1700-1759        1922  1900-1959        0.0       0.0           104.0   
1      0800-0859         934  0900-0959        0.0       0.0            79.0   
2      1500-1559        1656  1600-1659        0.0       0.0            76.0   
3      0600-0659         758  0700-0759        0.0       0.0            88.0   
4      1300-1359        1603  1600-1659        0.0       0.0           123.0   
...          ...         ...        ...        ...       ...             ...   
23401  0600-0659         715  0700-0759        0.0       0.0            90.0   
23402  1100-1159        1315  1300-1359        0.0       0.0            85.0   
23403  0600-0659         745  0700-0759        0.0       0.0            85.0   
23404  1700-1759        1915  1900-1959        0.0       0.0            85.0   
23405  1700-1759        1915  1900-1959        0.0       0.0           170.0   

       Flights Distance DistanceGroup  
0          1.0    209.0             1  
1          1.0    212.0             1  
2          1.0    209.0             1  
3          1.0    258.0             2  
4          1.0    696.0             3  
...        ...      ...           ...  
23401      1.0    328.0             2  
23402      1.0    361.0             2  
23403      1.0    361.0        

In [ ]:
df.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline ',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'Origin', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'Dest',
       'DestCityName', 'DestState', 'DestStateFips', 'DestStateName',
       'DestWac', 'CRSDepTime', 'DepTimeBlk', 'CRSArrTime', 'ArrTimeBlk',
       'Cancelled', 'Diverted', 'CRSElapsedTime', 'Flights', 'Distance',
       'DistanceGroup'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23406 entries, 0 to 23405
Data columns (total 43 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   Year                                     23406 non-null  int64  
 1   Quarter                                  23406 non-null  int64  
 2   Month                                    23406 non-null  int64  
 3   DayofMonth                               23406 non-null  int64  
 4   DayOfWeek                                23406 non-null  int64  
 5   FlightDate                               23406 non-null  object 
 6   Marketing_Airline_Network                23406 non-null  object 
 7   Operated_or_Branded_Code_Share_Partners  23406 non-null  object 
 8   DOT_ID_Marketing_Airline                 23406 non-null  int64  
 9   IATA_Code_Marketing_Airline              23406 non-null  object 
 10  Flight_Number_Marketing_Airline          23406

In [ ]:
Z =   ['FlightDate','Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
        'IATA_Code_Marketing_Airline', 'IATA_Code_Operating_Airline',
       'Origin', 'OriginCityName','OriginState', 'OriginStateName', 'Dest',
       'DestCityName', 'DestState', 'DestStateName', 'DepTimeBlk', 'ArrTimeBlk','Operating_Airline' ]
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in Z:
  if i in df.columns:
    df[i] = le.fit_transform(df[i])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23406 entries, 0 to 23405
Data columns (total 43 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   Year                                     23406 non-null  int64  
 1   Quarter                                  23406 non-null  int64  
 2   Month                                    23406 non-null  int64  
 3   DayofMonth                               23406 non-null  int64  
 4   DayOfWeek                                23406 non-null  int64  
 5   FlightDate                               23406 non-null  int64  
 6   Marketing_Airline_Network                23406 non-null  int64  
 7   Operated_or_Branded_Code_Share_Partners  23406 non-null  int64  
 8   DOT_ID_Marketing_Airline                 23406 non-null  int64  
 9   IATA_Code_Marketing_Airline              23406 non-null  int64  
 10  Flight_Number_Marketing_Airline          23406

In [ ]:
for col in df.columns:
    if df[col].dtype == 'object':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

df.corr()

Year  Quarter  Month  DayofMonth  \
Year                                      NaN      NaN    NaN         NaN   
Quarter                                   NaN      NaN    NaN         NaN   
Month                                     NaN      NaN    NaN         NaN   
DayofMonth                                NaN      NaN    NaN    1.000000   
DayOfWeek                                 NaN      NaN    NaN    0.058338   
FlightDate                                NaN      NaN    NaN    0.998842   
Marketing_Airline_Network                 NaN      NaN    NaN   -0.067971   
Operated_or_Branded_Code_Share_Partners   NaN      NaN    NaN   -0.067971   
DOT_ID_Marketing_Airline                  NaN      NaN    NaN    0.067971   
IATA_Code_Marketing_Airline               NaN      NaN    NaN   -0.067971   
Flight_Number_Marketing_Airline           NaN      NaN    NaN    0.060344   
Operating_Airline                         NaN      NaN    NaN   -0.040654   
DOT_ID_Operating_Airline                  NaN      NaN    NaN    0.069413   
IATA_Code_Operating_Airline               NaN      NaN    NaN   -0.040654   
Flight_Number_Operating_Airline           NaN      NaN    NaN    0.058405   
OriginAirportID                           NaN      NaN    NaN   -0.103022   
OriginAirportSeqID                        NaN      NaN    NaN   -0.103022   
OriginCityMarketID                        NaN      NaN    NaN   -0.063788   
Origin                                    NaN      NaN    NaN   -0.104816   
OriginCityName                            NaN      NaN    NaN   -0.066188   
OriginState                               NaN      NaN    NaN    0.028974   
OriginStateFips                           NaN      NaN    NaN    0.032186   
OriginStateName                           NaN      NaN    NaN    0.031252   
OriginWac                                 NaN      NaN    NaN   -0.074285   
DestAirportID                             NaN      NaN    NaN   -0.006369   
DestAirportSeqID                          NaN      NaN    NaN   -0.006369   
DestCityMarketID                          NaN      NaN    NaN    0.001623   
Dest                                      NaN      NaN    NaN   -0.005281   
DestCityName                              NaN      NaN    NaN    0.010969   
DestState                                 NaN      NaN    NaN    0.029521   
DestStateFips                             NaN      NaN    NaN    0.032466   
DestStateName                             NaN      NaN    NaN    0.031138   
DestWac                                   NaN      NaN    NaN   -0.059924   
CRSDepTime                                NaN      NaN    NaN   -0.023725   
DepTimeBlk                                NaN      NaN    NaN   -0.023375   
CRSArrTime                                NaN      NaN    NaN   -0.003216   
ArrTimeBlk                                NaN      NaN    NaN   -0.008670   
Cancelled                                 NaN      NaN    NaN    0.140568   
Diverted                                  NaN      NaN    NaN    0.023230   
CRSElapsedTime                            NaN      NaN    NaN   -0.012606   
Flights                                   NaN      NaN    NaN         NaN   
Distance                                  NaN      NaN    NaN   -0.035626   
DistanceGroup                             NaN      NaN    NaN   -0.033656   

                                         DayOfWeek  FlightDate  \
Year                                           NaN         NaN   
Quarter                                        NaN         NaN   
Month                                          NaN         NaN   
DayofMonth                                0.058338    0.998842   
DayOfWeek                                 1.000000    0.062332   
FlightDate                                0.062332    1.000000   
Marketing_Airline_Network                -0.406534   -0.076560   
Operated_or_Branded_Code_Share_Partners  -0.406534   -0.076560   
DOT_ID_Marketing_Airline                  0.406534    0.07

 # ***REGRESSION***

***PREDICTING ORIGIN***

***SIMPLE LINEAR REGRESSION***

In [ ]:
X = df.loc[:, ['OriginAirportSeqID']].values
X

array([[1329605],
       [1226402],
       [1161802],
       ...,
       [1105703],
       [1105703],
       [1105703]])

In [ ]:
Y = df.loc[:, ['Origin']].values
Y

array([[94],
       [64],
       [45],
       ...,
       [27],
       [27],
       [27]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score
y_pred = regressor.predict(X_test)
r2_score(Y_test, y_pred)

0.9956765424958705

In [ ]:
df.drop(['Year',	'Quarter',	'Month',	'DayofMonth', 'FlightDate','DestCityMarketID', 'Flight_Number_Marketing_Airline','DestCityName',	'DestState',	'DestStateFips',	'DestStateName',	'DestWac',	'CRSDepTime', 'OriginState',	'OriginStateFips',	'OriginStateName', 'DOT_ID_Operating_Airline', 'Flight_Number_Operating_Airline', 'Dest',	'DepTimeBlk',	'CRSArrTime',	'ArrTimeBlk',	'Cancelled', 'DestAirportID',	'DestAirportSeqID','Flights'], axis = 1, inplace = True)

In [ ]:
X = df.loc[:, ['DayOfWeek',	'Marketing_Airline_Network',	'Operated_or_Branded_Code_Share_Partners',	'DOT_ID_Marketing_Airline',	'IATA_Code_Marketing_Airline',		'IATA_Code_Operating_Airline',	'OriginAirportID',	'OriginAirportSeqID',	'OriginCityMarketID',	'OriginCityName',	'OriginWac',	'Diverted',	'CRSElapsedTime']].values
X

array([[  7.,   0.,   0., ...,  14.,   0., 104.],
       [  7.,   0.,   0., ...,  38.,   0.,  79.],
       [  7.,   0.,   0., ...,  21.,   0.,  76.],
       ...,
       [  3.,   1.,   1., ...,  36.,   0.,  85.],
       [  3.,   1.,   1., ...,  36.,   0.,  85.],
       [  3.,   1.,   1., ...,  36.,   0., 170.]])

In [ ]:
Y = df.loc[:, ['Origin']].values
Y

array([[94],
       [64],
       [45],
       ...,
       [27],
       [27],
       [27]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

***MULTIPLE LINEAR REGRESSION***

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score
y_pred = regressor.predict(X_test)
r2_score(Y_test, y_pred)

0.9962656692065385

***SUPPORT VECTOR REGRESSOR***

***DECISION TREE***

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y_test, Y_pred)

0.9999998909485561

***RANDOM FOREST***

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y_test, Y_pred)

0.9999999770991967

In [ ]:
data = np.array([0.98899, 0.99169, 0.99764, 1.0, 0.9999 ])

# providing an index
ser = pd.Series(data, index=['Simple Linear Regression', 'Multiple Linear Regression', 'SVM', 'DECSION_TREE', 'RANDOM_FOREST'])

print(ser)

Simple Linear Regression      0.98899
Multiple Linear Regression    0.99169
SVM                           0.99764
DECSION_TREE                  1.00000
RANDOM_FOREST                 0.99990
dtype: float64


In [ ]:
import pandas as pd
import numpy as np

# ***CLASSIFICATION***

In [ ]:
df = pd.read_csv('flight_data_2018_2024.csv')

<ipython-input-72-791efcd94eec>:1: DtypeWarning: Columns (11,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('flight_data_2018_2024.csv')


In [ ]:
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0      2024        1      1          14          7  2024-01-14   
1      2024        1      1          14          7  2024-01-14   
2      2024        1      1          14          7  2024-01-14   
3      2024        1      1          14          7  2024-01-14   
4      2024        1      1          14          7  2024-01-14   
...     ...      ...    ...         ...        ...         ...   
23401  2024        1      1          17          3  2024-01-17   
23402  2024        1      1          17          3  2024-01-17   
23403  2024        1      1          17          3  2024-01-17   
23404  2024        1      1          17          3  2024-01-17   
23405  2024        1      1          17          3  2024-01-17   

      Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
0                            UA                            UA_CODESHARE   
1                            UA                            UA_CODESHARE   
2                            UA                            UA_CODESHARE   
3                            UA                            UA_CODESHARE   
4                            UA                            UA_CODESHARE   
...                         ...                                     ...   
23401                        WN                                      WN   
23402                        WN                                      WN   
23403                        WN                                      WN   
23404                        WN                                      WN   
23405                        WN                                      WN   

       DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  Div5Airport  \
0                         19977                          UA  ...          NaN   
1                         19977                          UA  ...          NaN   
2                         19977                          UA  ...          NaN   
3                         19977                          UA  ...          NaN   
4                         19977                          UA  ...          NaN   
...                         ...                         ...  ...          ...   
23401                     19393                          WN  ...          NaN   
23402                     19393                          WN  ...          NaN   
23403                     19393                          WN  ...          NaN   
23404                     19393                          WN  ...          NaN   
23405                     19393                          WN  ...          NaN   

      Div5AirportID  Div5AirportSeqID Div5WheelsOn  Div5TotalGTime  \
0               NaN               NaN          NaN             NaN   
1               NaN               NaN          NaN             NaN   
2               NaN               NaN          NaN             NaN   
3               NaN               NaN          NaN             NaN   
4               NaN               NaN          NaN             NaN   
...             ...               ...          ...             ...   
23401           NaN               NaN          NaN             NaN   
23402           NaN               NaN          NaN             NaN   
23403           NaN               NaN          NaN             NaN   
23404           NaN               NaN          NaN             NaN   
23405           NaN               NaN          NaN             NaN   

      Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  Unnamed: 119  
0                  NaN            NaN         NaN         N           NaN  
1                  NaN            NaN         NaN         N           NaN  
2                  NaN            NaN         NaN         N           NaN  
3                  NaN            NaN         NaN         N           NaN  
4                  NaN            NaN         NaN         N           NaN  
...                ...            ...      

In [ ]:
df.dropna(axis = 1, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23406 entries, 0 to 23405
Data columns (total 43 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   Year                                     23406 non-null  int64  
 1   Quarter                                  23406 non-null  int64  
 2   Month                                    23406 non-null  int64  
 3   DayofMonth                               23406 non-null  int64  
 4   DayOfWeek                                23406 non-null  int64  
 5   FlightDate                               23406 non-null  object 
 6   Marketing_Airline_Network                23406 non-null  object 
 7   Operated_or_Branded_Code_Share_Partners  23406 non-null  object 
 8   DOT_ID_Marketing_Airline                 23406 non-null  int64  
 9   IATA_Code_Marketing_Airline              23406 non-null  object 
 10  Flight_Number_Marketing_Airline          23406

In [ ]:
Z = df.columns
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in Z:
  if df[i].dtype == 'object':
    df[i] = le.fit_transform(df[i])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23406 entries, 0 to 23405
Data columns (total 43 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   Year                                     23406 non-null  int64  
 1   Quarter                                  23406 non-null  int64  
 2   Month                                    23406 non-null  int64  
 3   DayofMonth                               23406 non-null  int64  
 4   DayOfWeek                                23406 non-null  int64  
 5   FlightDate                               23406 non-null  int64  
 6   Marketing_Airline_Network                23406 non-null  int64  
 7   Operated_or_Branded_Code_Share_Partners  23406 non-null  int64  
 8   DOT_ID_Marketing_Airline                 23406 non-null  int64  
 9   IATA_Code_Marketing_Airline              23406 non-null  int64  
 10  Flight_Number_Marketing_Airline          23406

In [ ]:
df

Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0      2024        1      1          14          7          13   
1      2024        1      1          14          7          13   
2      2024        1      1          14          7          13   
3      2024        1      1          14          7          13   
4      2024        1      1          14          7          13   
...     ...      ...    ...         ...        ...         ...   
23401  2024        1      1          17          3          15   
23402  2024        1      1          17          3          15   
23403  2024        1      1          17          3          15   
23404  2024        1      1          17          3          15   
23405  2024        1      1          17          3          15   

       Marketing_Airline_Network  Operated_or_Branded_Code_Share_Partners  \
0                              0                                        0   
1                              0                                        0   
2                              0                                        0   
3                              0                                        0   
4                              0                                        0   
...                          ...                                      ...   
23401                          1                                        1   
23402                          1                                        1   
23403                          1                                        1   
23404                          1                                        1   
23405                          1                                        1   

       DOT_ID_Marketing_Airline  IATA_Code_Marketing_Airline  ...  CRSDepTime  \
0                         19977                            0  ...        1738   
1                         19977                            0  ...         815   
2                         19977                            0  ...        1540   
3                         19977                            0  ...         630   
4                         19977                            0  ...        1300   
...                         ...                          ...  ...         ...   
23401                     19393                            1  ...         645   
23402                     19393                            1  ...        1150   
23403                     19393                            1  ...         620   
23404                     19393                            1  ...        1750   
23405                     19393                            1  ...        1725   

       DepTimeBlk  CRSArrTime  ArrTimeBlk  Cancelled  Diverted  \
0              12        1922          14        0.0       0.0   
1               3         934           4        0.0       0.0   
2              10        1656          11        0.0       0.0   
3               1         758           2        0.0       0.0   
4               8        1603          11        0.0       0.0   
...           ...         ...         ...        ...       ...   
23401           1         715           2        0.0       0.0   
23402           6        1315           8        0.0       0.0   
23403           1         745           2        0.0       0.0   
23404          12        1915          14        0.0       0.0   
23405          12        1915          14        0.0       0.0   

       CRSElapsedTime  Flights  Distance  DistanceGroup  
0               104.0      1.0     209.0              1  
1                79.0      1.0     212.0              1  
2                76.0      1.0     209.0              1  
3                88.0      1.0     258.0              2  
4               123.0      1.0     696.0              3  
...               ...      ...       ...            ...  
23401            90.0      1.0     328.0              2  
23402            85.0      1.0     361.0              2  
2

In [ ]:
df.drop(['Year',	'Quarter',	'Month',	'DayofMonth', 'FlightDate','DestCityMarketID', 'Flight_Number_Marketing_Airline','DestCityName',	'DestState',	'DestStateFips',	'DestStateName',	'DestWac',	'CRSDepTime', 'OriginState',	'OriginStateFips',	'OriginStateName', 'DOT_ID_Operating_Airline', 'Flight_Number_Operating_Airline', 'Dest', 'DestAirportID',	'DestAirportSeqID',], axis = 1, inplace = True)

In [ ]:
df.columns

Index(['DayOfWeek', 'Marketing_Airline_Network',
       'Operated_or_Branded_Code_Share_Partners', 'DOT_ID_Marketing_Airline',
       'IATA_Code_Marketing_Airline', 'Operating_Airline ',
       'IATA_Code_Operating_Airline', 'OriginAirportID', 'OriginAirportSeqID',
       'OriginCityMarketID', 'Origin', 'OriginCityName', 'OriginWac',
       'DepTimeBlk', 'CRSArrTime', 'ArrTimeBlk', 'Cancelled', 'Diverted',
       'CRSElapsedTime', 'Flights', 'Distance', 'DistanceGroup'],
      dtype='object')

In [ ]:
df['Marketing_Airline_Network'].unique()

array([0, 1])

In [ ]:
X = df.drop(['Marketing_Airline_Network'], axis = 1)
X= X.values

In [ ]:
Y = df.loc[:, ['Marketing_Airline_Network']].values
Y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

***LOGISTIC REGRESSION***

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[ 817  660]
 [ 316 2889]]


0.7915420760358821

***KNN***

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1475    2]
 [   0 3205]]


0.9995728321230244

***SUPPORT VECTOR MACHINE***

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1477    0]
 [   0 3205]]


1.0

***NAIVE BAYES***

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1477    0]
 [   0 3205]]


1.0

***DECISION TREE***

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1477    0]
 [   0 3205]]


1.0

***RANDOM FOREST***

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1477    0]
 [   0 3205]]


1.0

In [ ]:
data = np.array([0.911677,0.99822,1.0,1.0,1.0,1.0 ])

# providing an index
ser = pd.Series(data, index=['Logistic Regression', 'KNN', 'SVM', 'NAIVE_BAYES', 'DECSION_TREE', 'RANDOM_FOREST'])

print(ser)

Logistic Regression    0.911677
KNN                    0.998220
SVM                    1.000000
NAIVE_BAYES            1.000000
DECSION_TREE           1.000000
RANDOM_FOREST          1.000000
dtype: float64
